modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/MCTeamPotato/CorpseComplex-Unofficial/issues"
license="${mod_license}"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL=""
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="%{forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="curios"
    mandatory=false
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"
